### ISSUE TITLE
https://api.fish.audio/v1/tts

### ISSUE THREAD

**Issue by jhhhhkj** [AnyaCoder/fish-speech-gui#3] opened 2024-11-11 08:01 UTC
后端不存在，什么问题?

**Comment by AnyaCoder** [comment] 2024-11-11 14:04
httpx默认启用proxy的问题。你可以clone下最新的代码，已修复。

**Comment by qxevtnuko** [comment] 2024-12-03 13:59
I have also encountered the same problem, which is the new code cloned in the past two days
The test URL still reports an error and cannot connect to the backend. At first, I couldn't open the GUI interface when starting main.exe, but later I modified the code as shown in the picture before opening it. I don't know what the problem is
![fix](https://github.com/user-attachments/assets/ddcc1b61-7007-47a6-9c6c-2b1d63ddeb87)

**Comment by qxevtnuko** [comment] 2024-12-03 14:08
Is it related to the pkd_sources module   
![pkg](https://github.com/user-attachments/assets/425f6e17-f812-4cde-8b4a-290a423bfa38)

**Comment by AnyaCoder** [comment] 2024-12-08 03:31
#5 
It is caused by httpx version problem?

**Comment by qxevtnuko** [comment] 2024-12-08 03:56
> #5 是httpx版本问题导致的吗？
I don't know. I gave up researching this later. My friend asked me to help him deploy the fish-speech agent. Now it's at the last step and the Gradio interface has been brought up, but there is a bug when starting a conversation. Here is the issue link: https://github.com/fishaudio/fish-speech/issues/715. Could you help me take a look? Thank you.

**Comment by AnyaCoder** [comment] 2024-12-17 17:00
fixed in #4

**Closed as completed by AnyaCoder** 2024-12-17 17:00 UTC
